import type { Metadata } from "next";
import { Plus_Jakarta_Sans, DM_Mono } from "next/font/google";
import "./globals.css";
import { ORGANIZATION_SCHEMA, SITE_URL } from "@/lib/structuredData";

const jakarta = Plus_Jakarta_Sans({
  variable: "--font-jakarta",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

const dmMono = DM_Mono({
  variable: "--font-dm-mono",
  subsets: ["latin"],
  weight: ["400", "500"],
});

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "schedU — School Timetable Generator & Class Scheduling Software, Built with Human Intelligence",
    template: "%s · schedU",
  },
  description:
    "Free online timetable maker for schools, colleges & universities. Auto-generate conflict-free class schedules, teacher timetables & school routines in minutes — smarter than black-box AI, built with Human Intelligence from real school experience. CBSE, ICSE, IB, Cambridge, Common Core & every board.",
  // The phrases real users actually search — timetable maker, class scheduler,
  // school routine, period allocation — belong in titles/descriptions (Google
  // ignores the keywords meta tag, but other engines still read it).
  keywords: [
    "timetable generator", "school timetable maker", "class scheduling software",
    "timetable software", "school scheduling software", "class routine maker",
    "teacher timetable generator", "automatic timetable generator",
    "school timetable software free", "college timetable maker",
    "period allocation", "substitute teacher management", "teacher workload",
    "CBSE timetable", "ICSE timetable", "school master timetable",
    "AI timetable generator alternative", "exam timetable maker",
  ],
  openGraph: {
    type: "website",
    siteName: "schedU",
    // OG/Twitter image is generated by app/opengraph-image.tsx (next/og) —
    // most social platforms don't render SVG OG images, so this ships PNG.
  },
  twitter: {
    card: "summary_large_image",
  },
  // Google Search Console ownership verification (HTML-tag method).
  // The token is committed here as the permanent source of truth so
  // verification can NEVER be lost to an env-var change or a fresh deploy —
  // it is version-controlled and always emitted. The token is public (it
  // ships in the page HTML for anyone to read), so committing it is safe.
  // NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION can still override it if the
  // property is ever re-verified with a new token.
  verification: {
    google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION
      ?? "t_HVg1SLuoc0M_koE_e9UKPTmY1se_r2UKvKQchex28",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${jakarta.variable} ${dmMono.variable}`}>
      <body className="min-h-full">
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(ORGANIZATION_SCHEMA) }}
        />
        {children}
      </body>
    </html>
  );
}
