import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { buttonVariants } from "@/components/ui/button";
import { REGISTER_URL } from "@/lib/site";
import { cn } from "@/lib/utils";

export function CTA() {
  return (
    <section className="py-20 lg:py-28">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="rounded-2xl bg-primary px-6 py-16 text-center sm:px-16">
          <h2 className="mx-auto max-w-2xl text-3xl font-bold tracking-tight text-primary-foreground sm:text-4xl">
            Ready to build your next timetable in minutes?
          </h2>
          <p className="mx-auto mt-4 max-w-xl text-lg text-primary-soft">
            Join the institutions that have traded scheduling spreadsheets for
            conflict-free timetables generated by AI.
          </p>
          <div className="mt-10">
            <Link
              href={REGISTER_URL}
              className={cn(
                buttonVariants({ size: "lg" }),
                "bg-white text-primary hover:bg-primary-soft",
              )}
              aria-label="Start a free schedU trial"
            >
              Start Free Trial
              <ArrowRight className="size-5" />
            </Link>
          </div>
        </div>
      </div>
    </section>
  );
}
